title: Hello, world! I'm Sebastian Galonska
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cto.berlin" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sebastian Galonska # add your name
author-img: /sebastian-galonska-128x128.png # add your photo
about-author: I am a CTO, coach and conference speaker # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
#social-github:  # add your Github handle
social-linkedin: https://www.linkedin.com/in/sgalonska/ # add your Linkedin handle
social-email: hi@cto.berlin # add your Email address

# Disqus
#discus-identifier: sebastian_galonska # add your discus identifier

# Tracker
analytics: G-DM63FTV818 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

destination: docs
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
